config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  get 'admin/index'

  resources :categories
  resources :tags, except: [:index]
  resources :products, except: [:new]
  resources :carts, param: :product_id
  get '/orders/confirm', to: 'orders#update'
  get '/orders/instrucciones', to: 'orders#instrucciones'
  resources :orders, except: [:destroy]

  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create]
    resources :sessions, only: [:new, :create]
    delete '/sessions/logout', to: 'sessions#destroy', as: 'logout'
  end
end

app/views/shared/_flash.html.erb
<% if alert || notice %>
  <% color = alert ? 'bg-red-400' : 'bg-green-400' %>
  <div class="mt-28 fixed top-0 inset-x-0 m-4 z-30 pointer-events-none">
    <div class="flex flex-col items-end space-y-4">
      <div data-controller="alert" data-alert-dismiss-after-value="3000" data-alert-show-class="translate-x-0 opacity-100" data-alert-hide-class="translate-x-full opacity-0" class="ease-in-out duration-500 max-w-sm w-full shadow-lg rounded px-4 py-3 relative <%= color %> text-white pointer-events-auto translate-x-0 opacity-100">
        <div class="p-2">
          <div class="flex items-start">
            <div class="ml-3 w-0 flex-1 pt-0.5">
              <p class="text-sm leading-5 font-medium">
                <%= alert || notice %>
              </p>
            </div>
            <div class="ml-4 flex-shrink-0 flex">
              <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="flex bg-theme rounded-3xl items-center justify-center my-8 mx-4 p-8 gap-8">
  <%= image_tag 'icons/whatsappIcon.svg', width: 42, height: 42 %>
  <%= image_tag 'icons/instagramIcon.svg', width: 42, height: 42 %>
  <%= image_tag 'icons/facebookIcon.svg', width: 42, height: 42 %>
</footer>

app/views/shared/_header.html.erb
<header class="bg-theme h-24">
  <nav class="grid h-24 grid-cols-[1fr_3fr_repeat(2,1fr)] sm:grid-cols-12 content-center items-center place-items-center" aria-label="Global" data-controller="menu">
    <button class="sm:hidden" data-action="click->menu#toggle"> <%= image_tag asset_path('icons/sandwichMenu.svg'), width: 42, height: 42 %> </button>

    <%= link_to root_path, class: " sm:col-span-3" do %>
      <%= image_tag asset_path('ekisukiLogo.webp'), class: 'max-h-24 max-w-full' %>
    <% end %>
    <!--    MENU MOBILE-->
    <div class="sm:hidden absolute bg-slate-100/75 backdrop-blur-sm top-0 left-0 shadow z-10 h-full flex flex-col min-w-[100%] ease-in-out duration-500 p-5 -translate-x-full" data-menu-target="items">
      <button class="mb-2 text-left text-6xl text-theme" data-action="click->menu#toggle">&times;</button>
      <%= form_with url: products_path, method: :get do |form| %>
        <label class="relative block shadow-lg ring-2 ring-theme rounded-xl">
          <span class="sr-only">Buscar</span>
          <span class="absolute inset-y-0 right-0 flex items-center pr-2">
            <%= image_tag 'icons/searchIcon.svg', class: 'h-5 w-5 fill-slate-300', width: 42, height: 42 %>
          </span>
          <%= form.text_field :query_text, placeholder: 'Busca tu producto aqui', value: params[:query_text], class: "placeholder:italic placeholder:text-slate-400 block bg-white w-full border border-transparent rounded-xl py-2 pl-3 pr-9 focus:outline-none focus:border-transparent focus:ring-transparent focus:ring-1 sm:text-sm " %>
        </label>
      <% end %>

      <% if @categoryList %>
        <div class="flex flex-col justify-center p-4 mt-8 gap-2 bg-white rounded-lg">
          <h2 class="text-theme text-2xl">Categorias:</h2>
          <% @categoryList&.each do |category| %>
            <%= link_to category_path(category.id), class: "text-theme py-2", id: dom_id(category) do %>
              <p>
                <%= category.name %>  ►
              </p>
              <hr>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <section class="flex items-center justify-center mt-4 gap-8">
        <%= image_tag 'icons/whatsappIcon.svg', width: 50, height: 50 %>
        <%= image_tag 'icons/instagramIcon.svg', width: 50, height: 50 %>
        <%= image_tag 'icons/facebookIcon.svg', width: 50, height: 50 %>
      </section>
    </div>
    <!--  FIN DE MENU MOBILE  -->
    <div class="hidden sm:block sm:col-span-6 sm:w-11/12 md:w-3/5">
    <%= form_with url: products_path, method: :get do |form| %>
        <label class="relative block">
          <span class="sr-only">Buscar</span>
          <span class="absolute inset-y-0 right-0 flex items-center pr-2">
          <%= image_tag 'icons/searchIcon.svg', class: 'h-5 w-5 fill-slate-300', width: 42, height: 42 %>
        </span>
          <%= form.text_field :query_text, placeholder: 'Busca tu producto aqui', value: params[:query_text], class: "placeholder:italic placeholder:text-slate-400 block bg-white w-full border border-transparent rounded-3xl py-2 pl-3 pr-9 shadow-sm focus:outline-none focus:border-fuchsia-500 focus:ring-fuchsia-500 focus:ring-1 sm:text-sm " %>
        </label>
    <% end %>
    </div>

    <%= link_to new_session_path ,class:'justify-self-end mr-2 lg:mr-1' do %>
      <%= image_tag(Current.user.present? ? 'icons/salirIcon.svg' : 'icons/loginIcon.svg', width: 42, height: 42) %>
    <% end %>

    <%= image_tag 'icons/saleIcon.svg', class: 'hidden sm:block', width: 42, height: 42 %>
    <%= link_to carts_path, class: 'justify-self-start' do %>
      <%= image_tag 'icons/cartIcon.svg', width: 43, height: 43 %>
    <% end %>
  </nav>
</header>