config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  get 'admin/index'

  resources :categories
  resources :tags, except: [:index]
  resources :products, except: [:new]
  resources :carts, param: :product_id
  get '/orders/confirm', to: 'orders#update'
  get '/orders/instrucciones', to: 'orders#instrucciones'
  resources :orders, except: [:destroy]

  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create]
    resources :sessions, only: [:new, :create]
    delete '/sessions/logout', to: 'sessions#destroy', as: 'logout'
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :carts, dependent: :destroy
  validates :phone_number, presence: true, length: { is: 8 }
  validate :validate_name_presence
  def validate_name_presence
    if name.blank? || name.split.size < 2
      errors.add(:name, 'Debe ingresar al menos un nombre y un apellido')
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ destroy ]
  skip_before_action :protect_pages, only: %i[ create new update ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end
  def show
    @order = Order.find(params[:id])
    @product = Product.joins(:carts).where(carts: { user_id: @order.user_id, order_id: @order.id })
                      .select("products.*, carts.quantity as cart_quantity, carts.size as cart_size")
  end

  def update
    @order = Order.find_by(token: params[:token])
    encontrado = @order.present?
    previamenteConfirmada = @order&.confirmed
    if @order&.update(confirmed: true) and encontrado
      # Acción exitosa
      if not previamenteConfirmada
        OrderMailer.notifyUs.deliver_later
      end
      @mensaje = "Gracias por confirmar, tu orden sera despachada en breve!"
    else
      # Error en la actualización
      @mensaje = "El token no es valido! Porfavor revisa tu url."
    end
  end

  # GET /orders/new
  def new
    @order = Order.new

    @last_order = Order.where(user_id: Current.user.id).last

    if @last_order
      @last_order_name = @last_order.name
      @last_order_phone_number = @last_order.phone_number
      @last_order_email = @last_order.email
      @last_order_shipping_address = @last_order.shipping_address
      @last_order_note = @last_order.note
    end
  end

  # POST /orders or /orders.json
  def create
    @product = Product.joins(:carts).where(carts: { user_id: Current.user.id, order_id: nil }).select("products.*, carts.quantity as cart_quantity")
    @total = @product.map { |p| p.price * p.cart_quantity }.sum + 35
    require 'securerandom'

    @order = Order.new(order_params.merge(user_id: Current.user.id, total: @total, token: SecureRandom.urlsafe_base64(32,padding: false)))

    respond_to do |format|
      # if verify_recaptcha(model: @order) && @order.save
      if verify_recaptcha(model: @order) && @order.save
        # traer la carreta del usuario actual con order_id null
        @carts = Cart.where(user_id: Current.user, order_id: nil )
        @carts.each do |cart|
          cart.update(order_id: @order.id)
        end
        OrderMailer.with(user: Current.user, order: @order, cart: @carts.to_a).confirmOrder.deliver_later
        format.html { redirect_to '/orders/instrucciones', notice: "Gracias! por favor revisa tu correo." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def order_params
    params.require(:order).permit(:name, :phone_number, :email, :shipping_address, :note)
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="bg-white px-6 text-theme md:w-5/6 md:mx-auto">
  <h1 class="font-bold text-2xl mt-4">Datos de entrega</h1>
  <%= form_with(model: order, class: "contents") do |form| %>
    <% if order.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(order.errors.count, "error") %> no permitio crear la orden:</h2>
        <ul>
          <% order.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5 flex flex-col gap-4">
      <div class="flex align-center items-center gap-2">
        <%= image_tag 'icons/orderForm/name.svg', class: 'w-8' %>
        <%= form.label :name, 'Nombre y apellido de persona que recibe' %>
      </div>
      <%= form.text_field :name, value: @last_order_name, class: 'placeholder:italic placeholder:text-slate-400 block bg-white w-full border-2 border-theme rounded-xl py-2 pl-3 pr-9 shadow-lg focus:outline-none focus:border-fuchsia-500 focus:ring-fuchsia-500 focus:ring-1 sm:text-sm' %>
    </div>
    <div class="my-5 flex flex-col gap-4">
      <div class="flex align-center items-center gap-2">
        <%= image_tag 'icons/orderForm/phone.svg', class: 'w-8' %>
        <%= form.label :phone_number, 'Teléfono' %>
      </div>
      <%= form.text_field :phone_number, value: @last_order_phone_number, class: 'placeholder:italic placeholder:text-slate-400 block bg-white w-full border-2 border-theme rounded-xl py-2 pl-3 pr-9 shadow-lg focus:outline-none focus:border-fuchsia-500 focus:ring-fuchsia-500 focus:ring-1 sm:text-sm'  %>
    </div>
    <div class="my-5 flex flex-col gap-4">
      <div class="flex align-center items-center gap-2">
        <%= image_tag 'icons/orderForm/mail.svg', class: 'w-8' %>
        <%= form.label :email, 'Correo' %>
      </div>
      <%= form.email_field :email, value: @last_order_email, class: 'placeholder:italic placeholder:text-slate-400 block bg-white w-full border-2 border-theme rounded-xl py-2 pl-3 pr-9 shadow-lg focus:outline-none focus:border-fuchsia-500 focus:ring-fuchsia-500 focus:ring-1 sm:text-sm'  %>
    </div>
    <div class="my-5 flex flex-col gap-4">
      <div class="flex align-center items-center gap-2">
        <%= image_tag 'icons/orderForm/addres.svg', class: 'w-8' %>
        <%= form.label :shipping_address, 'Direccion de entrega' %>
      </div>
      <%= form.text_field :shipping_address, value: @last_order_shipping_address, class: 'placeholder:italic placeholder:text-slate-400 block bg-white w-full border-2 border-theme rounded-xl py-2 pl-3 pr-9 shadow-lg focus:outline-none focus:border-fuchsia-500 focus:ring-fuchsia-500 focus:ring-1 sm:text-sm'  %>
    </div>
    <div class="my-5 flex flex-col gap-4">
      <div class="flex align-center items-center gap-2">
        <%= image_tag 'icons/orderForm/notes.svg', class: 'w-8' %>
        <%= form.label :note, 'Datos de entrega adicionales, como referencias o instrucciones' %>
      </div>
      <%= form.text_area :note, value: @last_order_note, class: 'placeholder:italic placeholder:text-slate-400 block bg-white w-full border-2 border-theme rounded-xl py-2 pl-3 pr-9 shadow-lg focus:outline-none focus:border-fuchsia-500 focus:ring-fuchsia-500 focus:ring-1 sm:text-sm'  %>
    </div>
    <div class="flex justify-center mt-4 mb-1 p-4">
      <%= recaptcha_tags(noscript: false) %>
    </div>
    <div class="flex justify-center mt-4 mb-1 p-4">
      <%= form.submit 'Ordenar', class: 'px-6 py-3 rounded-xl drop-shadow-lg bg-theme' %>
    </div>
  <% end %>
</div>

app/views/orders/_index.html.erb
<div class="mx-auto md:w-2/3 w-full my-4">

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Ordenes</h1>
  </div>

  <div id="orders" class="min-w-full">
    <%= render @orders %>
  </div>
</div>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>" class="flex my-3 items-center gap-2 lg:gap-8">
  <span class="text-2xl text-gray-700">Orden #<%= order.id %></span>
  <% if action_name != "show" %>
    <% if order.confirmed %>
      confirmada✅
      <% else %>
      no confirmada🚫
    <% end %>
    |
    <%= order.updated_at.in_time_zone("Central America").strftime('%d/%m/%Y - %I:%M %p') %>
    |
    total: Q<%= order.total %>

    <%= link_to "Ver Orden", order, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

    <%#= link_to 'Edit this order', edit_order_path(order), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/orders/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing order</h1>

  <%= render "form", order: @order %>

  <%= link_to "Show this order", @order, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to orders", orders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/orders/instrucciones.html.erb
<%= image_tag "GraciasPorLaCompra.webp", class:"mx-auto w-full md:w-3/4 mt-2"%>

app/views/orders/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", order: @order %>

  <div class="flex justify-center mb-1 p-4">
    <%= link_to 'Regresar al carrito', carts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium text-theme" %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <h2 class="text-2xl">
      Orden #<%= @order.id %>
    </h2>
    <div class="relative overflow-x-auto text-theme">

    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <% @product.each do |product| %>
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 text-theme">
        <th scope="row" class="px-6 py-2 md:p-2 font-medium text-gray-900 whitespace-nowrap dark:text-white">
          <% if product.photos.attached? %>
            <%= link_to product_path(product.id), class: "my-8", id: dom_id(product) do %>
              <%= image_tag product.photos[0], width: 200 %>
            <% end %>
          <% end %>
        </th>
        <td class="px-2 py-2 md:p-0 text-sm">
          <div class="flex flex-col">
            <%= product.title %>
            <br>
            <% if product.cart_size %>
              tamaño: <%= product.cart_size %>
              <br>
            <% end %>
            Q<%= product.price %> c/u
            <br>
            sub-total Q<%= product.price * product.cart_quantity %>
          </div>
        </td>
        <td class="px-4 py-2 md:p-0">
          <%= form_with model: @cart, url: cart_path(product_id: product.id), method: :patch do |form| %>
            <%= form.select :quantity, options_for_select((1..5).to_a, product.cart_quantity), {}, { class: "border-0 rounded-xl bg-theme", disabled: true} %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </table>
    </div>

    <div class="flex flex-col">
      <h3 class="text-2xl">Datos de cliente</h3>
      <span class="text-gray-600 ml-2 underline">Direccion de entrega:</span>
      <%= @order.shipping_address %>
      <span class="text-gray-600 ml-2 underline">Numero de Telefono:</span>
      <%= @order.phone_number %>
      <span class="text-gray-600 ml-2 underline">email:</span>
      <%= @order.email %>
      <span class="text-gray-600 ml-2 underline">nombre:</span>
      <%= @order.name %>
      <span class="text-gray-600 ml-2 underline">Total:</span>
      Q<%= @order.total %>
    </div>
    <%= link_to 'Edit this order', edit_order_path(@order), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this order', order_path(@order), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Regresar', admin_index_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

  </div>

</div>

app/views/orders/update.html.erb
<h1><%= @mensaje %></h1>