config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  get 'admin/index'

  resources :categories
  resources :tags, except: [:index]
  resources :products, except: [:new]
  resources :carts, param: :product_id
  get '/orders/confirm', to: 'orders#update'
  get '/orders/instrucciones', to: 'orders#instrucciones'
  resources :orders, except: [:destroy]

  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create]
    resources :sessions, only: [:new, :create]
    delete '/sessions/logout', to: 'sessions#destroy', as: 'logout'
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_one_attached :photo
  has_many :taggings, dependent: :destroy
  has_many :products, through: :taggings
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]
  skip_before_action :protect_pages, only: [:index, :show]
  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  def show
    @categoryList = Category.all
    @category = Product.joins(:taggings => :tag).where(:tags => { :id => @tag }).distinct
    @product = Product.joins(:taggings => :tag).where(:tags => { :id => @tag }).distinct
    @tagName = @tag.name
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to admin_index_path, notice: "Tag Creado." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to admin_index_path, notice: "Tag actualizada." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tag/1
  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to admin_index_path, notice: "Tag eliminado." }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tag_params
    params.require(:tag).permit(:name, :photo)
  end
end

app/views/tags/_form.html.erb
<%= form_with(model: tag, class: "contents") do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(tag.errors.count, "error") %> no permitieron al tag guardarse.</h2>

      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :photo, 'Foto' %>
    <%= form.file_field :photo %>
  </div>

  <div class="inline">
    <%= form.submit "Guardar Tag", class: "rounded-lg py-3 px-5 bg-fuchsia-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/tags/_index.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Tags</h1>
    <%= link_to 'Agregar Tag', new_tag_path, class: "rounded-lg py-3 px-5 bg-fuchsia-600 text-white block font-medium" %>
  </div>

  <div id="categories" class="min-w-full grid grid-cols-2">
    <%= render @tags %>
  </div>
</div>

app/views/tags/_tag.html.erb
<div id="<%= dom_id tag %>">
  <p class="my-5">
    <strong class="font-medium mb-1">Nombre:</strong>
    <%= tag.name %>
  </p>

  <% if action_name != "show" %>
    <%= image_tag tag&.photo, width: 200 if tag.photo.attached?%>
    <%= link_to 'Editar tag', edit_tag_path(tag), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Eliminar tag', tag_path(tag), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium", data: {
      turbo_method: :delete,
      turbo_confirm: "Estas seguro de eliminarla? "
    } %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/tags/_tagsFooter.html.erb
<section class="grid grid-cols-2 md:flex md:justify-center gap-4 p-4">
  <% @tag.each do |tag| %>
    <%= link_to tag_path(tag.id), class:"tag",id: dom_id(tag) do %>
      <%= image_tag tag&.photo, class: "clip-square md:h-48 md:max-w-full" if tag.photo.attached? %>
    <% end %>
  <% end %>
</section>

app/views/tags/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editar Tag</h1>

  <%= render "form", tag: @tag %>

  <%= link_to "Regresar", admin_index_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tags/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Nuevo tag</h1>

  <%= render "form", tag: @tag %>

  <%= link_to 'Regresar', admin_index_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tags/show.html.erb
<%= render 'categories/categoriesList' %>
<div class="sm:hidden basis-full text-gray-600 mx-4 mt-4">
  <span class="font-bold text-xl">
      <%= @tag.name %>
  </span>
</div>

<div class="md:w-4/6 md:mx-auto grid grid-cols-2 gap-4 p-4 sm:grid-cols-4">
  <div class="hidden sm:block basis-full text-gray-600 mx-4 mt-4 sm:col-span-4">
    Todos los productos relacionados con la etiqueta:
    <span class="font-bold text-xl">
        <%= @tag.name %>
    </span>
  </div>
  <% @product.each do |product| %>
    <%= link_to product_path(product.id), class: "my-2 flex flex-col justify-center hover:shadow-xl hover:rounded-xl ease-in-out duration-300 hover:scale-105", id: dom_id(product) do %>
      <%= image_tag product&.photos[0], class: "clip-square" if product.photos.attached? %>
      <span class="text-theme text-center"><%= product.title %></span>
      <span class="text-theme text-xl font-bold text-center">Q<%= product.price %></span>
    <% end %>
  <% end %>
</div>