config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  get 'admin/index'

  resources :categories
  resources :tags, except: [:index]
  resources :products, except: [:new]
  resources :carts, param: :product_id
  get '/orders/confirm', to: 'orders#update'
  get '/orders/instrucciones', to: 'orders#instrucciones'
  resources :orders, except: [:destroy]

  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create]
    resources :sessions, only: [:new, :create]
    delete '/sessions/logout', to: 'sessions#destroy', as: 'logout'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_one_attached :photo
  has_many :products, dependent: :restrict_with_exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  skip_before_action :protect_pages, only: [:index, :show]
  # GET /categories/new
  def new
    @category = Category.new
  end

  def index
    @category = Category.all
    @tag = Tag.order("RANDOM()").limit(5)


    #producto mas vendido es el ID que mas se repite en los carritos que han sido vendidos
    @topSellerProduct = Product.find(Cart.where.not(order_id: nil)
                            .group(:product_id)
                            .order('count_product_id DESC')
                            .count('product_id')
                            .first
                          &.first)
  end

  # GET /categories/1/edit
  def show
    @categoryList = Category.all
    @tagLista = Tag.joins(:products => :category).where(:categories => { :id => @category }).distinct
    @tag = Tag.order("RANDOM()").limit(5)
    @product = Product.where(:category_id => @category)
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_index_path, notice: "Categoria Creada." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      pp category_params
      if @category.update(category_params)
        format.html { redirect_to admin_index_path, notice: "Categoria actualizada." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to admin_index_path, notice: "Categoria eliminada." }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :photo, :isClothes)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categoriesCircles.html.erb
<section class="grid grid-cols-2 sm:flex sm:justify-center gap-8 md:gap-20 p-4 text-center text-theme drop-shadow-lg">
  <% @category.each do |category| %>
    <!--    id:"<%#= dom_id category %>"-->
    <%= link_to category_path(category.id), class: "", id: dom_id(category) do %>
      <%= image_tag category&.photo, class: "clip-circle hover:bg-grey-600 sm:h-32 sm:max-w-full" if category.photo.attached? %>
      <p class="text-theme">
        <%= category.name %>
      </p>
    <% end %>
  <% end %>
</section>

app/views/categories/_categoriesList.html.erb
<section class="sm:flex justify-evenly gap-4 text-fuchsia-600 hidden sm:pb-3" style="background-color: #F1DAFC">
  <% @categoryList.each do |category| %>
    <%= link_to category_path(category.id), class: "categoria gap-4", id: dom_id(category) do %>
      <p>
        <%= category.name %>
      </p>
    <% end %>
  <% end %>
</section>

app/views/categories/_category.html.erb
 <div id="<%= dom_id category %>">
  <p class="my-5">
    <strong class="font-medium mb-1">Nombre:</strong>
    <%= category.name %>
  </p>

  <% if action_name != "show" %>
    <%= image_tag category&.photo, width: 200 if category.photo.attached?%>
    <%= link_to 'Editar la categoria', edit_category_path(category), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Eliminar esta categoria', category_path(category), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium", data: {
      turbo_method: :delete,
      turbo_confirm: "Estas seguro de eliminarla? "
    } %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/categories/_categoryHeader.html.erb
<section class="flex justify-evenly gap-4 text-fuchsia-600" style="background-color: #F1DAFC">
  <% @categoryList.each do |category| %>
    <%= link_to category_path(category.id), class: "categoria gap-4", id: dom_id(category) do %>
      <p>
        <%= category.name %>
      </p>
    <% end %>
  <% end %>
</section>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> no permitieron a la categoria guardarse.</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="my-5">
    <%= form.label :isClothes, 'Es Ropa? esto mostrara seleccion de tamaño' %>
    <%= form.check_box :isClothes %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-fuchsia-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/categories/_index.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Categorias</h1>
    <%= link_to 'Agregar Categoria', new_category_path, class: "rounded-lg py-3 px-5 bg-fuchsia-600 text-white block font-medium" %>
  </div>

  <div id="categories" class="min-w-full grid grid-cols-2">
    <%= render @categories %>
  </div>
</div>

app/views/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editar Categoria</h1>

  <%= render "form", category: @category %>

  <%= link_to "Regresar", admin_index_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<%= image_tag "landingpage/yaAbrimos.webp", class:"mx-auto w-full md:w-3/4 mt-2"%>

<%= render 'categories/categoriesCircles' %>

<section class="grid grid-cols-1 sm:w-4/5 md:w-4/5 sm:mx-auto  sm:grid-cols-2 sm:justify-center sm:text-center text-theme p-4 justify-center">
  <article class="text-center">
    <div class="">
      <h2 class="text-4xl my-4">Como Ordenar</h2>
      <p>Unicamente agregas al carrito los articulos, completas los datos requerridos
        y al mandar el pedido se te estara enviando un correo de confirmacion de orden!
        Ten en cuenta por el momento realizamos enviós en el area de la capital, si tu orden
        es a un seccion donde no tenemos cobertura se te notificará por correo</p>
    </div>
  </article>
  <article class="grid grid-cols-1 justify-items-center text-center">
    <h2 class="text-4xl mt-6 mb-4">Lo mas Vendido</h2>
    <%= image_tag @topSellerProduct&.photos[0], width: 250 if @topSellerProduct&.photos&.attached? %>
  </article>
<!--  <article class="grid grid-cols-1 justify-items-center sm:col-span-2 sm:flex sm:items-center">-->
    <%#= image_tag @topSellerProduct&.photos[0],class:'hidden sm:block', width: 200 if @topSellerProduct&.photos&.attached? %>
<!--    <p>-->
<!--      Somo una tienda en línea con mas de 10 año de experiencia, empezamos como un pequeño-->
<!--      emprendimiento, realizando bisutería con diferentes materiales como porcelana fría, poco-->
<!--      a poco nos fuimos expandiendo hasta tener productos sublimados e impresos.-->
<!--    </p>-->
<!--  </article>-->
</section>

<%= render 'tags/tagsFooter' %>

<section class="grid grid-cols-2 md:flex md:justify-center gap-2 md:gap-8 p-4">
  <%= image_tag "landingpage/enviosguatemala.webp", class: "clip-square md:h-48 md:max-w-full" %>
  <%= image_tag "landingpage/pagoContraEntrega.webp", class: "clip-square md:h-48 md:max-w-full" %>
  <%= image_tag "landingpage/productosNovedosos.webp", class: "clip-square md:h-48 md:max-w-full" %>
  <%= image_tag "landingpage/productosNuevos.webp", class: "clip-square md:h-48 md:max-w-full" %>
</section>

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Agregar Categoria</h1>

  <%= render "form", category: @category %>

  <%= link_to 'Back to categories', admin_index_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/show.html.erb
<%= render 'categories/categoriesList' %>
<div class="sm:hidden basis-full text-gray-600 mx-4 mt-4">
  <span class="font-bold text-xl">
    <%= @category.name %>
  </span>
</div>
<div class="flex md:w-4/6 md:mx-auto sm:grid sm:grid-cols-4">
  <div class="hidden sm:flex sm:flex-col gap-4 sm:w-3/5 basis-full mx-4 mt-4">
    <span class="font-bold text-gray-600 text-xl">
      <%= @category.name %>
    </span>
    <% @tagLista.each do |tag| %>
      <%= link_to tag_path(tag.id), class: "text-theme hover:text-fuchsia-300 ml-4 hover:underline", id: dom_id(tag) do %>
        <%= tag.name %>
      <% end %>
    <% end %>
  </div>
  <div class="grid grid-cols-2 gap-4 p-4 sm:grid-cols-2 sm:col-span-3 md:grid-cols-3">
    <% @product.each do |product| %>
      <%= link_to product_path(product.id), class: "my-2 flex flex-col justify-center hover:shadow-xl hover:rounded-xl ease-in-out duration-300 hover:scale-105", id: dom_id(product) do %>
        <%= image_tag product&.photos[0], class: "clip-square" if product.photos.attached? %>
        <span class="text-theme text-center"><%= product.title %></span>
        <span class="text-theme text-xl font-bold text-center">Q<%= product.price %></span>
      <% end %>
    <% end %>
  </div>
</div>
<hr class="text-green-500 bg-blue-600 sm:hiden"/>
<%= render 'tags/tagsFooter' %>